version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    cap_add: 
      - SYS_NICE
    env_file:
      - ./.env_mysql
    ports:
      - "4306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  php:
    container_name: "php"
    build: ./php
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
  
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
    restart: always
    ports:
      - "18088:80"
    depends_on:
      - php